# Generated by Django 3.1.7 on 2021-03-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210329_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='No Bio'),
            preserve_default=False,
        ),
    ]
