# Generated by Django 3.1.7 on 2021-03-25 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('related_skills', models.JSONField()),
                ('difficulty', models.IntegerField()),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('deadline', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaded_projects', to=settings.AUTH_USER_MODEL)),
                ('project_members', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('asignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('asigner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.project')),
            ],
        ),
    ]
