# Generated by Django 3.1.7 on 2021-03-25 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20210324_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaded_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
