# Generated by Django 3.1.7 on 2021-03-29 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='school_logos')),
                ('leaders', models.ManyToManyField(related_name='school_lead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
