# Generated by Django 3.1.7 on 2021-04-21 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='leaders',
        ),
        migrations.AddField(
            model_name='school',
            name='coms',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='overseer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overseer_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='proj_man',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='school_members',
            field=models.ManyToManyField(related_name='schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='tech_spec',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techincal_specialist_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='tut_out',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoring_outreach_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
